### ISSUE TITLE
What are sigma, u and mu referring to in the trainedModel object?

### ISSUE THREAD

**Issue by timyitong** [nicolaspanel/node-svm#17]
I am trying to use "node-svm", but I am a bit lost in the output of the trainedModel. Could anyone explain a bit what are signma, u and mu?

I suspect one of them must be alpha (the parameter for each support vector) in the dual form of SVM, but which one? And what do the rest of the parameters mean?

**Comment by nicolaspanel** [comment]
`sigma` and `mu` are used for features [mean-normalization](http://en.wikipedia.org/wiki/Normalization_%28statistics%29) (if enabled)

`u` is used for [PCA reduction](http://en.wikipedia.org/wiki/Principal_component_analysis) (if enabled)

see [https://github.com/nicolaspanel/node-svm#parameters-and-options](readme) for more information about other parameters
