### ISSUE TITLE
multi-class

### ISSUE THREAD

**Issue by pakkolol** [nicolaspanel/node-svm#18]
Hello, i was wondering if node-svm can perfom multi-class classification by itself, or do i need to perform it using 1-vs-1 or 1-vs-all. This is the example of a dataset:

```
[
 [[ 262, 333, 1421855978.249186, 25.64758, 0.431, 0 ], 1],
 [[ 262, 326, 1421855978.26529, 25.64758, 0.431, 0 ], 1],
 [[ 262, 326, 1421855978.282071, 25.64758, 0.431, 0 ] 1]
.....

```

This a short example of the features of one class, and i have many many classes, thousands to be exact, and every class has around 20 examples or features.
Im using node-svm with:
```
Classifier: CSVC
C: [0.03125, 0.125, 0.5, 2, 8],
kernelType: 'RBF',  
gamma: [0.03125, 0.125, 0.5, 2, 8],
nFold: 5,               
normalize: true
```
When i train a class what i do is, i select the same number of negative samples from other classes has i have positive from the new class, and train the classifier with positive and negative samples, thus making the classifier binary.
My question if i need to do this, or i can just train node svm with all the classes all together and the implementation alone already does this for me.

**Comment by nicolaspanel** [comment]
You should use built-in multiclass support with the entire dataset.

Note: each class must be represented by an unique integer. Example:
   - person0 => 0
   - person1 => 1
   - person2 => 2
   - ...

Since the number of feature is small (6) you should disable PCA:
```javascript
Classifier: CSVC
C: [0.03125, 0.125, 0.5, 2, 8],
kernelType: 'RBF',  
gamma: [0.03125, 0.125, 0.5, 2, 8],
nFold: 5,               
normalize: true,
reduce: false
```

**Comment by pakkolol** [comment]
Thank you for your help, i am already getting better results!! But if i am constantly adding new classes, i have to constantly be training a new classification model? Any idea on how can i improve this a bit
Thanks for your help

**Comment by nicolaspanel** [comment]
I think there is no other solution when using SVM.
Maybe you should take a look to other machine learning techniques (see http://scikit-learn.org/stable/supervised_learning.html#supervised-learning)
Best regards
