### ISSUE TITLE
ld: library not found for -lgcc_s.10.5 error when installing

### ISSUE THREAD

**Issue by tuananh** [nicolaspanel/node-svm#21]
`npm install node-svm --save` fails with error `ld: library not found for -lgcc_s.10.5`. Any idea?
        -
        > node-svm@2.1.5 install /Users/tuananh/hq_src/fraud-fight/node_modules/node-svm
        > node-gyp rebuild

          CXX(target) Release/obj.target/addon/src/libsvm/svm.o
          CXX(target) Release/obj.target/addon/src/addon.o
          CXX(target) Release/obj.target/addon/src/node-svm/node-svm.o
          SOLINK_MODULE(target) Release/addon.node
        ld: library not found for -lgcc_s.10.5
        clang: error: linker command failed with exit code 1 (use -v to see invocation)
        make: *** [Release/addon.node] Error 1
        gyp ERR! build error
        gyp ERR! stack Error: `make` failed with exit code: 2
        gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
        gyp ERR! stack     at emitTwo (events.js:87:13)
        gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
        gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
        gyp ERR! System Darwin 15.0.0
        gyp ERR! command "/usr/local/bin/iojs" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
        gyp ERR! cwd /Users/tuananh/hq_src/fraud-fight/node_modules/node-svm
        gyp ERR! node -v v2.4.0
        gyp ERR! node-gyp -v v2.0.1
        gyp ERR! not ok
        npm ERR! Darwin 15.0.0
        npm ERR! argv "/usr/local/bin/iojs" "/usr/local/bin/npm" "install" "node-svm" "--save"
        npm ERR! node v2.4.0
        npm ERR! npm  v2.13.0
        npm ERR! code ELIFECYCLE

        npm ERR! node-svm@2.1.5 install: `node-gyp rebuild`
        npm ERR! Exit status 1
        npm ERR!
        npm ERR! Failed at the node-svm@2.1.5 install script 'node-gyp rebuild'.
        npm ERR! This is most likely a problem with the node-svm package,
        npm ERR! not with npm itself.
        npm ERR! Tell the author that this fails on your system:
        npm ERR!     node-gyp rebuild
        npm ERR! You can get their info via:
        npm ERR!     npm owner ls node-svm
        npm ERR! There is likely additional logging output above.

        npm ERR! Please include the following file with any support request:
        npm ERR!     /Users/tuananh/hq_src/fraud-fight/npm-debug.log

**Comment by tuananh** [comment]
Seem to be an issue with OS X 10.11 and Xcode 6. Install Xcode 7 beta or use this as temporary fix.

    cd /usr/local/lib
    sudo ln -s ../../lib/libSystem.B.dylib libgcc_s.10.5.dylib

**Comment by nicolaspanel** [comment]
tx for your feed back :+1: 

Which version of nodejs / iojs do you use?

**Comment by tuananh** [comment]
i'm using `iojs v2.4.0`

**Comment by ielgnaw** [comment]
Thanks @tuananh

**Comment by codepython** [comment]
it works~
Thanks.
