### ISSUE TITLE
Predictions always 0

### ISSUE THREAD

**Issue by csysmans** [nicolaspanel/node-svm#28]
Hi,

First of all, big fan of the module! It's really simple, customizable and is quite fast, compared to other SVM implementations.
However, I'm having problems with the dataset I currently use ([input.txt](https://github.com/nicolaspanel/node-svm/files/152975/input.txt)).

The code I am currently using to create and train the SVM is:

```
// Create SVM
var clf = new svm.SVM({
	type: 'EPSILON_SVR',
	kernel: 'POLY',
	gamma: 0.25,
    c: 1, 
    normalize: false,
    reduce: false,
    kFold: 1
});

// Train SVM
console.log("Training...");
clf.train(svmData).done(function () {
	// Predict
	console.log("Predicting...");
    svmData.forEach(function(ex){
        var prediction = clf.predictSync(ex[0]);
       	console.log('%d => %d', ex[1], prediction);
    });
});
```

No matter what variation of SVM options I try, the prediction I receive is always 0.
Could the problem be that my data is to small (I pre-normalize my data between -1 and 1)?

Kind regards!

**Comment by nicolaspanel** [comment]
Hi, 

The dataset do not seems to be normalized. You should definitely normalize it (using `normalize`=true).

Also, `RBF` kernel is usually a better choice than `POLY`.

Can you try with following parameters (defaults) :
```js
var clf = new svm.SVM({
    type: 'EPSILON_SVR',
    kernel: 'RBF',
    normalize: true,
    reduce: false,
    kFold: 4
});
```

**Comment by csysmans** [comment]
Hello,

So i've changed the SVM constructor to your code and commented my own normalization code. 
The resulting input is this: [input2.txt](https://github.com/nicolaspanel/node-svm/files/153041/input2.txt)

However, now I receive the following error:
```
Assertion failed: (tout->IsNumber()), function setSvmProblem, file ../src/node-svm/node-svm.h, line 347.
Abort trap: 6
```

Thanks for your help!

**Comment by nicolaspanel** [comment]
Forget it.

There is a typo in `clf` initialization. You are using `type` when you actually meant  `svmType`  params [see this for more  info](https://github.com/nicolaspanel/node-svm#parameters-and-options).

It is very likely that it is trying to use a Classifier (C_SVC) instead of a Regressor (EPSILON_SVC)

This should work:
```js
var clf = new svm.SVM({
    svmType: 'EPSILON_SVR',
    kernel: 'RBF',
    normalize: true,
    reduce: false,
    kFold: 4
});
```

Note: it is actually the same as:
```js
var clf = new svm.EpsilonSVR({
    reduce: false
});
```

**Comment by nicolaspanel** [comment]
Note that your last issue is because your dataset contains strings

**Comment by nicolaspanel** [comment]
It should work as expected right now. If not, let me know.
Best regards

**Comment by csysmans** [comment]
You are absolutely right. The problem was indeed that my dataset contained strings (problem while reading the CSV file containing the data)! Thanks for all your help!
