### ISSUE TITLE
Limitation on amount of features

### ISSUE THREAD

**Issue by csysmans** [nicolaspanel/node-svm#29]
Hi, 

I'm having another problem.
The SVM works great, but is there a limitation on the amount of features?
I use the following input data: [svmData.txt](https://github.com/nicolaspanel/node-svm/files/154314/svmData.txt),
I create the SVM like so:
```
// Create SVM
var clf = new svm.SVM({
    svmType: 'NU_SVR',
    kernel: 'RBF',
    normalize: true,
    reduce: false,
    kFold: 4,
    cacheSize: 1000
});

// Train SVM
console.log("Training...");
var lastPercentage = "0.0";
clf.train(svmData)
.progress(function(rate){
	var percentage = (Math.round(rate*1000)/10).toFixed(1);
	if(lastPercentage != percentage){
		console.log("Training...(" + percentage + "%)");
		lastPercentage = percentage;
	}
})
.done(function () {
	console.log("Training done...");
});
```

The execution of the program gets terminated abruptly at 99%. I receive no errors or warnings.
When I modify the data by removing one of the features (11 features instead of 12), the execution works as expected.

Kind regards

**Comment by csysmans** [comment]
Apparently it only works with 11 features, if I remove the last one. Is there something wrong with the data I provided? The SVM keeps hanging around 99.6%.

**Comment by nicolaspanel** [comment]
There is no limitation on the number of features so check your data.
tip:  `null` is not a `Number` ;)

**Comment by csysmans** [comment]
Oh my god, for shame!
Don't know how i missed that one "null" in my data...
Thanks!
