### ISSUE TITLE
Node6 support

### ISSUE THREAD

**Issue by wenq1** [nicolaspanel/node-svm#32]
Hi NicolasPanel

When updating to Node6.0, a huge amount of error is thrown:

Also please upgrade graceful-fs to ^4.0.0 to suppress the depreciation warnings.

Security context: 0x1287ef1c9e59 <JS Object>#0#
    1: .node [module.js:568] [pc=0x3d9744c377c4] (this=0x1902f98d9431 <an Object with map 0x335eb18161>#1#,module=0x3360d238dc61 <a Module with map 0x335ebb2001>#2#,filename=0x3360d238dbf9 <String[73]: SampleProj/node_modules/node-svm/build/Release/addon.node>)
    2: load [module.js:458] [pc=0x3d9744a396f2] (this=0x3360d238dc61 <a Module with map 0x335ebb2001>#2#,filename=0x3360d238dbf9 <String[73]: SampleProj/node_modules/node-svm/build/Release/addon.node>)
    3: tryModuleLoad(aka tryModuleLoad) [module.js:417] [pc=0x3d9744a3921d] (this=0x1287ef104189 <undefined>,module=0x3360d238dc61 <a Module with map 0x335ebb2001>#2#,filename=0x3360d238dbf9 <String[73]: SampleProj/node_modules/node-svm/build/Release/addon.node>)
    4: _load [module.js:409] [pc=0x3d9744a34e02] (this=0x1902f98d9559 <JS Function Module (SharedFunctionInfo 0x1902f9825909)>#3# 1: v8::Template::Set(v8::Local<v8::Name>, v8::Local<v8::Data>, v8::PropertyAttribute)
 2: NodeSvm::Init(v8::Local<v8::Object>)
 3: node::DLOpen(v8::FunctionCallbackInfo<v8::Value> const&)
 4: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&))
 5: v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::(anonymous namespace)::BuiltinArguments<(v8::internal::BuiltinExtraArguments)1>)
 6: v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*)
 7: 0x3d974490961b
(node) v8::ObjectTemplate::Set() with non-primitive values is deprecated
(node) and will stop working in the next major release.

**Comment by nicolaspanel** [comment]
Are you using node-svm@2.1.7?

I'm using node v6.1.0 (npm v3.8.6) and there is no error during installation (just few warnings).
Could you copy/paste the exact output from npm?

**Comment by wenq1** [comment]
My description was wrong - it is fine during installation but gives warning when run.

**Comment by wenq1** [comment]
And yes, it is node-svm 2.1.7.

**Comment by nicolaspanel** [comment]
ok, thanks

**Comment by wenq1** [comment]
I've sent in a pull request.

**Comment by nicolaspanel** [comment]
#33

**Comment by nicolaspanel** [comment]
see PR #33
