### ISSUE TITLE
unable to predict from load previous model

### ISSUE THREAD

**Issue by BoChengHuang** [nicolaspanel/node-svm#34]
Hello, I train a data set and store it into other folder. (in index.js)
After that, I  create a file called predict.js, main code is like:

`var persistedModel = JSON.parse(fs.readFileSync('./model/poker_sim_test.json'));`
`var clf = new svm.NuSVC({ model: persistedModel });`
`var prediction = clf.predict(guess);`

when I run it I face a problem that:

assert.js:89
  throw new assert.AssertionError({
  ^
AssertionError: false == true
    at NuSVC.SVM.predict (/Users/ives/Downloads/SVM_PokerHand/node_modules/node-svm/lib/core/svm.js:147:5)

How can I fix problems.

Thanks!!

**Comment by nicolaspanel** [comment]
To restore an existing prediction model you should use ` svm.restore` function.

Example:
```js
var svm = require('node-svm');
var persistedModel = JSON.parse(fs.readFileSync('./model/poker_sim_test.json'));
 var clf = svm.restore(persistedModel);
```

BR

**Comment by BoChengHuang** [comment]
Thank you but I still face this...

assert.js:89
throw new assert.AssertionError({
^
AssertionError: false == true
at NuSVC.SVM.predict (/Users/ives/Downloads/SVM_PokerHand/node_modules/node-svm/lib/core/svm.js:147:5)

Thanks!!

**Comment by BoChengHuang** [comment]
my test code is [here](https://gist.github.com/BoChengHuang/6a97870cefee589be215657e33907184), train and predict in a js file.

**Comment by nicolaspanel** [comment]
Try this instead:
```js
nodesvm.read(pathToTrainingData).then(function (dataset) {
    var clf = new nodesvm.NU_SVC({
            kFold: 4,
            normalize: false,
            reduce: false,
            kernelType: 'RBF',
            gamma: [0.03125, 0.125, 0.5, 2, 8]
      });
      clf.train(dataset).spread(function (model, report) {
            fs.writeFileSync('./model/poker_sim_test.json', JSON.stringify(model));
      }).then(function(){
            var persistedModel = JSON.parse(fs.readFileSync('./model/poker_sim_test.json'));
            var restoredClf = nodesvm.restore(persistedModel);
            restoredClf.predictSync([4, 10, 4, 11, 4, 1, 4, 13, 4, 12]);
      });
});
```

**Comment by BoChengHuang** [comment]
It seems to appear another error

Assertion failed: (elt->IsNumber()), function setModel, file ../src/node-svm/node-svm.h, line 229.
Abort trap: 6

my dataset is like this:
9 1:1 2:10 3:1 4:11 5:1 6:13 7:1 8:12 9:1 10:1
.
.
.

sorry for bothering
Thanks!

**Comment by nicolaspanel** [comment]
seem this error comes from your dataset but I can't help you with that...

**Comment by BoChengHuang** [comment]
Hello I can use the model from external file latter.

I originally use [this](https://github.com/nicolaspanel/node-svm/issues/7) and it can generate a model but can't predict as above discussion.

Latter I create a model file by 'node-svm train [train file] [model path]'.

And I use the sane dataset and the same prediction code, then everything works.

FYI

thank you!!!

**Comment by nicolaspanel** [comment]
Thank you for your feedback!
BR
