### ISSUE TITLE
Error: Module version mismatch.

### ISSUE THREAD

**Issue by mimorisuzuko** [nicolaspanel/node-svm#36]
I tried this module on Electron(v1.4.0). I got the error as blow. 

![2016-10-31 20 07 01](https://cloud.githubusercontent.com/assets/12094729/19852263/aff393be-9fa5-11e6-9412-4f119b168eaa.png)

Also, I tried `electron-rebuild` script(`./node_modules/.bin/electron-rebuild`). However, I got the same error with running Electron. I would like to know the appropriate Electron version.

**Comment by nicolaspanel** [comment]
Hi @mimorisuzuko and sorry for the delay.
To make sure the error do not come from electron itself, could you try to install node-svm alone using `npm install --save node-svm` command.
Best regards

**Comment by mimorisuzuko** [comment]
I have already installed it with `npm install --save node-svm` when I open this issue. However, I got this error.

**Comment by nicolaspanel** [comment]
could you try to run one of the node-svm example, such as [classification-basic-example](https://github.com/nicolaspanel/node-svm/blob/master/examples/classification-basic-example.js), independently from electron

```
$ mkdir ~/test-node-svm
$ cd ~/test-node-svm
$ npm install node-svm
$ node node_modules/node-svm/examples/classification-basic-example.js
```

**Comment by mimorisuzuko** [comment]
I can use this module without Electron. However, I cannot run it on Electron.

**Comment by nicolaspanel** [comment]
I cant help you on this since I know nothing about electron, sorry.
