### ISSUE TITLE
Train over sparse data

### ISSUE THREAD

**Issue by anagnoad** [nicolaspanel/node-svm#38]
Hi,

I am new to node-svm and I'm looking for a way to train my model over sparse arrays. For example, in a typical IR scenario, where the features are not known, and each column is essentially a tf*idf score or equivalent. Would it be possible to use a sparse format for the rows of the training model?

Thanks,
-Antonis

**Comment by nicolaspanel** [comment]
Hi, 
Sorry but this won't be possible with the current implementation...
Best regards
