### ISSUE TITLE
CPU and GPu

### ISSUE THREAD

**Issue by danielduckworth** [nicolaspanel/node-svm#39]
Hi, I'm assuming this uses the machine's CPU for training the mode?

Is it possible to configure it to use GPU instead?

**Comment by nicolaspanel** [comment]
This project is just a wrapper around [libsvm](https://www.csie.ntu.edu.tw/~cjlin/libsvm/) => no gpu support out of the box.

It seems that [this project](https://github.com/MKLab-ITI/CUDA) explored how to use cuda to improve performance but I never try it myself and it does not seems actively maintained...
