### ISSUE TITLE
Intuition behind retained dimensions value

### ISSUE THREAD

**Issue by lucasfanning** [nicolaspanel/node-svm#40]
How I can interpret retained dimensions contained in report bellow ? :

        accuracy: 0.994,
        fscore: 0.9918918918918919,
        recall: 0.9892183288409704,
        precision: 0.993660855784469,
        class: {
                '1': {
                        precision: 0.993660855784469,
                        recall: 0.9968203497615262,
                        fscore: 0.9952380952380951,
                        size: 629
                },
                '-1': {
                        precision: 0.994579945799458,
                        recall: 0.9892183288409704,
                        fscore: 0.9918918918918919,
                        size: 371
                }
        },
        size: 1000,
        reduce: true,
        retainedVariance: 0.9928844043087963,
        retainedDimension: 3,
        initialDimension: 13

Thanks!

**Comment by nicolaspanel** [comment]
default behavior use [principal component analysis](https://en.wikipedia.org/wiki/Principal_component_analysis) to reduce the dimension of the inputs while maintaining the information (ie retainedVariance).

Then, if `retainedDimension`  is much lower than `initialDimension` then you can deduce that your input data (ie features) are highly correlated.

To disable PCA you can set `reduce` option to `false`.

BR

**Comment by lucasfanning** [comment]
Thanks so much !!
