### ISSUE TITLE
Prediction separately from training

### ISSUE THREAD

**Issue by pavlosero** [nicolaspanel/node-svm#46]
How do I predict separately from training.
My code is following
` var svm = require('node-svm');
var so = require("stringify-object");
var filename = "dataset.ds"
var model_trained;
var clf = new svm.CSVC({
  gamma:[0.01, 0.1],
  c:8,
  kFold:4,
  normalize: true,
  kernelType: 'linear'
});

svm.read(filename)
  .then(function (dataset){
    console.log("start training...");
    return clf.train(dataset)
  })
  .spread(function(model,report){
    console.log("SVM trained. \n Report: \n%s", so(report));
  })

  console.log(clf.isTrained());
  // output false
`
I can't do it because my model results not trained

**Comment by nicolaspanel** [comment]
See https://github.com/nicolaspanel/node-svm/blob/master/examples/save-prediction-model-example.js
